name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  requirements:

    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/

      # Runs a single command using the runners shell
      - name: SET autorun.sh
        run: |
              chmod +x autorun.sh
              ./autorun.sh

